// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juyfnafhrjlvzktsgylt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1eWZuYWZocmpsdnprdHNneWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mjk2MTgsImV4cCI6MjA2NjUwNTYxOH0.VSY8CrhcusM37AseE0S-xJz9KgkwFF1HYCesu7CAevU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);